### ISSUE TITLE
BWEB Restructure

### ISSUE THREAD

**Issue by Cmccrave** [Cmccrave/BWEB#11]
General help needed, BWEB is currently organized like a monkey wrote the code. I can't head this issue as I am that monkey.

**Comment by impie66** [comment]
Have you tried turning it off and on again?

**Comment by Cmccrave** [comment]
Unfortunately that made the problem worse, it appears to upset the BWEB gods.

**Comment by kant2002** [comment]
@Cmccrave I think this project/library could greatly benefit from having tests. Gods of testing that way could trap the monkey.

**Comment by Cmccrave** [comment]
Completed. Glad it's over.
