### ISSUE TITLE
Destination doesn't generate walls

### ISSUE THREAD

**Issue by Cmccrave** [Cmccrave/BWEB#13]
Need to explore options on how to deal with chokes that are unbuildable (possibly iterate closer to area->Top() until a suitable location is found).

**Comment by MicroDK** [comment]
Does it iterate away fromt the choke? Then at some point it should find buildable positions.

**Comment by Cmccrave** [comment]
Fixed this in local version, added check to make sure our origin for building a Wall is buildable, if not it iterates closer to area->Top(). Will push when ready.
