### ISSUE TITLE
Issue with creep

### ISSUE THREAD

**Issue by kant2002** [Cmccrave/BWEB#19]
MicroDK report on Discord: 
Another thing which is not related to BWEB... creep tend not to spread all out on the map. On Icarus it stops at a certain distance from the nat choke even if I put a hatch there

**Comment by Cmccrave** [comment]
Same as with issue #9 , looking for any help on estimating creep spreading.

**Comment by MicroDK** [comment]
Yah, same as #9. This is a general BW / map thing... but BWEB must be aware of where the creep can spread to. This also holds for in-base build positions, where the creep does not spread all the way to the edges. I do not know what the rules are for creep spread. Maybe it only spread to buildable positions... if we are lucky... :)

**Comment by bftjoe** [comment]
Maybe extract the algorithm from openbw?

**Comment by Cmccrave** [comment]
Will not be adding creep/pylon power to BWEB, it will remain a planning library and not a decision making library.
