### ISSUE TITLE
Issue with Icarus map

### ISSUE THREAD

**Issue by kant2002** [Cmccrave/BWEB#20]
Again MicroDK
playing around with BWEB... it seems i does not generate a wall in natural on Icarus 9 o'clock position. All other positions work.

**Comment by MicroDK** [comment]
Thanks... you made the bug report before I had the change. ;)

**Comment by Cmccrave** [comment]
![image](https://user-images.githubusercontent.com/25108498/39977479-3413a592-5708-11e8-8978-db6eeb20e7e8.png)

Fixed, closing.
