### ISSUE TITLE
Remove Zerg specific wall rule

### ISSUE THREAD

**Issue by MicroDK** [Cmccrave/BWEB#21]
Change Wall.cpp line 227 https://github.com/Cmccrave/BWEB/blob/master/Wall.cpp#L227 to 
`if (piece.second == UnitTypes::Protoss_Pylon)`

This will make better zerg walls and defenses are not positioned in the mineral line or completely not added because of not enough space around the natural.

Icarus 6 o'clock
<img width="483" alt="Screen_Shot_2018-04-04_at_00 45 57" src="https://user-images.githubusercontent.com/1037224/38457402-4ad8730a-3a90-11e8-80ba-5276ba2e5548.png">

Icarus 3 o'clock
<img width="483" alt="screen_shot_2018-04-03_at_23 44 20" src="https://user-images.githubusercontent.com/1037224/38457383-119a086a-3a90-11e8-9720-48d7f92b55a8.png">

**Comment by Cmccrave** [comment]
Added this in local version, looks to be working fine.
