### ISSUE TITLE
Evo is not placed below Hatch in the choke

### ISSUE THREAD

**Issue by MicroDK** [Cmccrave/BWEB#22]
1. Evo and Hatch in wall.
2. Map Icarus 3 o'clock position.
3. Change Wall.cpp line 227 https://github.com/Cmccrave/BWEB/blob/master/Wall.cpp#L227 to `if (piece.second == UnitTypes::Protoss_Pylon)`

Should the Evo not have been placed below the Hatch in this wall? It seems there is enough space and it will be closer to the center of the choke as the code seems to try to minimize the distance to the choke center.

<img width="483" alt="screen shot 2018-04-06 at 00 38 54" src="https://user-images.githubusercontent.com/1037224/38457224-d4e15b50-3a8d-11e8-84dd-77e9974d0015.png">

Green: BWTA area
Red: BWTA choke
Orange: BWEM choke

**Comment by Cmccrave** [comment]
I believe this had to do with how I was handling pathing, will check tonight.

**Comment by Cmccrave** [comment]
@MicroDK Same for this, test and let me know if it's fixed.

**Comment by MicroDK** [comment]
Yes it is fixed. :D

<img width="478" alt="screen shot 2018-04-12 at 19 47 06" src="https://user-images.githubusercontent.com/1037224/38694585-58a4675c-3e8a-11e8-8956-aff13db73555.png">

**Comment by Cmccrave** [comment]
Forgot to close this, let me know if this issue pops up again.
