### ISSUE TITLE
Good zerg simcity / wall for reference

### ISSUE THREAD

**Issue by MicroDK** [Cmccrave/BWEB#23]
For reference, this is a good simcity / wall for zerg. Sunkens a bit away from natural hatch to make room for larva and units. Buildings are positioned in the area between the natural choke, main choke and natural hatch.

<img width="483" alt="screen shot 2018-04-08 at 20 30 31" src="https://user-images.githubusercontent.com/1037224/38471115-fc6e7eac-3b6c-11e8-9c6f-66c27a120bf6.png">

**Comment by Cmccrave** [comment]
Newest local version is behaving similarly, but could use some tweaking.

**Comment by Cmccrave** [comment]
Could use testing with newest version @MicroDK, let me know if I can close.

**Comment by MicroDK** [comment]
Ok, much better zerg walls! And very fast even with a path. :)

But I would like to have the wall moved so all buildings are behind the natural choke as much as possible. This is Python 9 o'clock position. Creep stop spreading just outside the choke, so it can be difficult to place buildings there for zerg.

<img width="479" alt="screen shot 2018-04-12 at 19 13 47" src="https://user-images.githubusercontent.com/1037224/38694838-fac9ffec-3e8a-11e8-9e07-38242a266e60.png">

Also, it will move the sunken positions closer to the natural hatch, so zerg can place sunkens there early before the creep have finish spreading. In this picture, the first sunken was placed outside the sunken space because the creep had not spread enough.

<img width="481" alt="screen shot 2018-04-12 at 19 39 28" src="https://user-images.githubusercontent.com/1037224/38695032-74af230a-3e8b-11e8-8751-45846384de92.png">

**Comment by Cmccrave** [comment]
Python sucks for walls, I hate it so much! I'll have to try looking into some different parameters for finding positions to help with this, thanks!

**Comment by Cmccrave** [comment]
Based on our discussion in discord and recent fixes, closing this as the placement is drastically improved. Re-open any map specifics for me.
