### ISSUE TITLE
Issue with Python

### ISSUE THREAD

**Issue by MicroDK** [Cmccrave/BWEB#24]
Version 1.0.2
No wall with zerg in 12 o'clock position.

<img width="486" alt="screen shot 2018-04-12 at 19 20 42" src="https://user-images.githubusercontent.com/1037224/38694441-ed790bd6-3e89-11e8-8852-60ec341e4517.png">

**Comment by Cmccrave** [comment]
![image](https://user-images.githubusercontent.com/25108498/39977469-209d8d8e-5708-11e8-8ce0-b0505cbdd015.png)

Fixed, closing.
