### ISSUE TITLE
Creep is not considered for Zerg buildings

### ISSUE THREAD

**Issue by Cmccrave** [Cmccrave/BWEB#9]
Not sure on the resolution for this, could be done the same way as Pylon power is in McRave or could be dealt with on a "spreading timer" basis. If the timer approach is chosen, BWEB will need to be used in onFrame as well.

**Comment by Cmccrave** [comment]
Or we would need an algorithm that can look at a frame count for a Hatchery/Colony and know how and when it will expand.

**Comment by BryanSWeber** [comment]
As a note, I've changed it locally to use pylon power. I'd want a test case where I know it's a certifiable problem, if one has shown up I'd be happy to see if it's improved.

**Comment by Cmccrave** [comment]
Will not be adding creep/pylon power to BWEB, it will remain a planning library and not a decision making library.
